### ISSUE TITLE
Can't get the logger to work

### ISSUE THREAD

**Issue by sderuiter** [Concordium/concordium-transaction-logger#8]
- I have Portainer running on Ubuntu  20.04. 
- I have the docker version of the Concordium-node running (updated to 4.2.1, up to date). This node runs on a bridge network in Portainer. 
I've installed the transaction logger from Docker hub (concordium/transaction-logger:0.3.1-0), it's also running on a bridge network. 
- As TRANSACTION_LOGGER_NODES I've set http://localhost:10000

Result after 5 sec:

Error: channel closed

I'm assuming this is related to the node and not the db?

What am I doing wrong?

**Comment by abizjak** [comment]
But this command is run from your host system, not from the container right?

**Comment by abizjak** [comment]
To give you a helpful answer we need to know how exactly you've set up networking for your containers.
